[package]
name = "cryptography"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "s1q1_convert_hex_to_base64"

[[bin]]
name = "s1q2_fixed_xor"

[dependencies]
base64 = "0.22.0"
hex = "0.4.3"
lazy_static = "1.4.0"
openssl = "0.10.64"
